### PR TITLE
Next button stuck issue fix where the trecounter id is not there

### PR DESCRIPTION
**Pull request by mahmed0715**
From #1120 with a users message https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1120#issuecomment-534967409

### CODE REVIEW

**Comment by norbertschuler** [comment]
I am sorry, but this just fixed the wrong suggestion results we retrieve on the staging server where the treecounterId is missing due to wrong mock-up data - compare https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1217

Please test your patch using https://test.trilliontreecampaign.org/ as the backend. I still experience a problem then when trying to call the API `https://test.trilliontreecampaign.org/api/v1.3/de/giftDonation/1/create`.

**Comment by mahmed0715** [comment]
You are right, thats why I kept both in there, you see the code
sugession.treecounterId || sugession.id, 
so in where we have treecounterid it will use that if thats not present in somewhere like staging, we can just keep going with the id.
@norbertschuler

**Comment by mahmed0715** [comment]
And this is not the fix for api call, this is the next button fix reported by a client , see in https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1120#issuecomment-534967409

**Comment by norbertschuler** [comment]
Ok, sorry, I was sure this does not happen on production, but if a user has complained about it, maybe I was wrong.

**Comment by norbertschuler** [comment]
We should close this pull request. I am pretty sure `id` and `treecounterid` are different values on production and that we would use a wrong value to reference the `treecounterid` on production with this patch.

**Pull request closed without merging**
