### PR TITLE
#1304 global currency selector

### PR DESCRIPTION
**Pull request by mahmed0715**
Draft: #1304 
Please check the currency selector, how it work.
@sagararyal

### CODE REVIEW

**Comment by mahmed0715** [comment]
@sagararyal we want to do the change for native app also in the same PR? same design?

**Comment by sagararyal** [comment]
@mahmed0715 
going to screen to select trees, gets default project currency auto selected.

  
Screen Shot 2019-09-25 at 11 37 43 AM

**Comment by mahmed0715** [comment]
@sagararyal @norbertschuler Currency selector will honor users profile currency(meaning user not logged in and changed currency , when user logged in the profile currency will overwrite the previously saved value)

**Comment by mahmed0715** [comment]
@sagararyal we can not use other language than en|de at least for now. so setting other language will not be effective at this stage. @norbertschuler explained this in the older pr #1355

**Comment by mahmed0715** [comment]
@harshvitra can you please fix the icon issue on safari, That would be great.

**Comment by norbertschuler** [comment]
```
ERROR in ./app/components/Menu/index.js
Module not found: Error: Can't resolve 'react-select' in '/Users/norbertschuler/Development/PFTP/treecounter-app/app/components/Menu'
 @ ./app/components/Menu/index.js 21:19-42
```

**Comment by norbertschuler** [comment]
Also eslint is now more severe:
```
/home/circleci/ttc-app/app/components/Menu/index.js
  260:17  error  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
  270:17  error  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank

```

**Comment by norbertschuler** [comment]
I got a crash when trying to donate as a logged out user without having changed any settings (German as language, USB as currency): https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1484

```
TypeError: (0 , _utils.formatNumber)(...).replace is not a function
    at TreeCountSelector.render (TreeCountSelector.js:164)
```

**Comment by norbertschuler** [comment]
Another problem testing (logged out user in Chrome on MacOS): My initial language (probably derived from my browser) is German. I tried to switch to English and the website got refreshed, but it's loading again in German and the dropdown is also still showing German. So I am not able to switch to English language.

**Comment by norbertschuler** [comment]
I will continue checking https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1485

**Comment by norbertschuler** [comment]
@mahmed0715 Do we want to close this PR now in favor of #1485 or do you want to keep the comment of @sagararyal?

**Comment by mahmed0715** [comment]
We can close this PR I think, @norbertschuler

**Pull request closed without merging**
