### PR TITLE
Image not visible when update tree and image not update

### LINKED ISSUE #2209: Editing registered trees with images is broken
**Describe the bug**
If you added a tree with the app, the image is stored as an contribution type image and therefore has a different pathname on the CDN servers. The current form of the web client still tries to load it from the same source as the project images.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to 'My forest'
2. Click on a self registered tree with an image
3. See error

**Expected behavior**
Load the image from the CDN server as expected.

**Screenshots**
Bildschirmfoto 2020-04-18 um 18 10 17

**Desktop (please complete the following information):**
- OS: lates MacOS
 - Browser: latest Chrome
 - Plant-for-the-Planet App Version 1.3.2

**Additional info**
If you check for `project` in our codebase you will find there the CDN image is still used as a constant - while this is o.k. for project images, it is wrong if the code also deals with images of self-registered trees:
Bildschirmfoto 2020-04-18 um 18 12 10

### LINKED ISSUE #2210: Uploading images for registered trees is broken
**Describe the bug**
Uploading an image for registered trees does not work anymore either when adding new trees or when editing existing trees.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to 'Register tree' or 'My forest'->'Update'
2. Choose an image
3. See error

**Expected behavior**
Upload new images.

**What actually happens**
The form is submitted, but the image is not updated.

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser latest Chrome
 - Plant-for-the-Planet App Version 1.3.2

### PR DESCRIPTION
**Pull request by sanjayradadiya**
Fixes #2209
Fixes #2210

Changes in this pull request:
- Image not visible and image not update when edit a tree 

@norbertschuler @harshkurra

### CODE REVIEW

**Comment by hkurra** [comment]
@sanjayradadiya you mentioned me by mistake, but changes are fine to me, I still remember this bug, server returns image path with a different key, 
it is always good to remove the console from production code, but you guys can also integrate the babel plugin which will automatically remove the console while building, if I am not wrong we have integrated that plugin long time ago

**Comment by norbertschuler** [comment]
> @sanjayradadiya you mentioned me by mistake, but changes are fine to me, I still remember this bug, server returns image path with a different key,
> it is always good to remove the console from production code, but you guys can also integrate the babel plugin which will automatically remove the console while building, if I am not wrong we have integrated that plugin long time ago

@harshkurra Thank you for having a look. We still have the plugin to remove console.log, but we should also not log to much in development as this makes the code running quiet slow sometimes. Also I replaced almost every console.log with a debug function with can be deactivated with a debug environment flag to quickly test the performance with console.log output on development.

**Comment by norbertschuler** [comment]
Maybe image management on the native apps for registered trees is not fully functional yet. Trying to remove an image by editing an user contribution and removing the image displayed does not work for me (the user contribution had two images, but only one is displayed in the native apps).

**Comment by sanjayradadiya** [comment]
Hey @jmiridis can you please check this ?
**Request URL:** https://app-development.plant-for-the-planet.org/api/v1.3/en/plantContributions/307279

**Payload:**`{"plant_contribution":{"plantDate":"2020-05-05","treeClassification":"","treeSpecies":"fsd","treeScientificName":"","treeCount":1,"contributionMeasurements":[],"contributionImages":[{"id":1142,"image":"5eb0e22bc971c854519353.jpeg","description":null},{"id":1141,"image":"5eb0e22934744946654348.jpeg","description":null}],"geoLocation":"geoLongitude=72.83117&geoLatitude=21.17026&country=IN","plantProject":""}}`

**response:**`{"merge":{"contribution":[{"id":307279,"contributionType":"planting","cardType":"planting","treeCount":1.0,"plantDate":"2020-05-05","geoLongitude":72.83117,"geoLatitude":21.17026,"country":"IN","contributionImages":[{"id":1141,"image":"5eb0e22934744946654348.jpeg","description":null},{"id":1142,"image":"5eb0e22bc971c854519353.jpeg","description":null},{"id":1143,"image":"5eb0e241ed2c2010840371.jpeg","description":null}],"contributionMeasurements":[],"treeType":"fsd","treeSpecies":"fsd","treeClassification":null,"treeScientificName":null,"mayUpdate":true,"isPending":false,"plantProjectId":null,"treecounterId":156687,"context":null,"geoLocation":"geoLongitude=72.83117&geoLatitude=21.17026&country=IN","ndviUid":null,"geometry":null}]}}`

When I remove one image but response of update api sending three contribution images it's not updating let me know If I am passing wrong things

And this API also sending same response 
**Request URL:** https://app-development.plant-for-the-planet.org/api/v1.1/en/loadUserProfile

**Comment by jmiridis** [comment]
The issue of deleting contribution images has been fixed.
Using the payload above provided by Sanjay, I was able to delete the last image.
Testing is advisable.

**Comment by norbertschuler** [comment]
> The issue of deleting contribution images has been fixed.
> Using the payload above provided by Sanjay, I was able to delete the last image.
> Testing is advisable.

Sorry, this does not work well

- [ ] The client can not correctly update its state with the answer given (it tries to merge the contribution of the API response with less images, but the deleted image entry inside the user contribution won't get removed from the clients state - I assume the `mergeEntities` or `normalize` functionality not being able to update the objects correctly). For all other _delete_ functions we get some `unlink` or `delete` objects from the backend to clean up the client state which we don't get in this case as the image is only a nested object inside the user contribution. But without such response from the backend our client does not clean up itself.

- [ ] The backend deleted all images if you try to delete them with the **web** client as probably the payload is not correctly sent compared with updating the user contribution with the native app - in fact **any** update of the user contribution with the **web** client deletes the images due to the wrong payload now:

- web clients payload (having three images, deleting one and keeping two):
Bildschirmfoto 2020-05-06 um 10 15 21

- backend response without images:
Bildschirmfoto 2020-05-06 um 10 14 59

- native app payload  (having three images, deleting one and keeping two):
Bildschirmfoto 2020-05-06 um 10 12 24

- backend response:
Bildschirmfoto 2020-05-06 um 10 12 46

**Pull request merged**
