### PR TITLE
Feature/contextual donations design

### PR DESCRIPTION
**Pull request by harshvitra**
Design Ready with all the functionalities. 

Only need to implement and integrate the API. Comment on the designs. 

**Localisation is left, creating draft so others can see while I'll do the localisation of text.** 

To test Credit card use number - 4111111111111111 (Visa) 5555555555554444 (MasterCard) with any future expiry date.

### CODE REVIEW

**Comment by harshvitra** [comment]
To Do - 

- [ ] Optimize Credit Card Images
- [ ] Localisation of Images
- [ ] Passing Data between different pages

**Comment by harshvitra** [comment]
Screenshot_1569876567
Screenshot_1569876575
Screenshot_1569876602
Screenshot_1569876607
Screenshot_1569876612
Screenshot_1569876615
Screenshot_1569876638
Screenshot_1569876673
Screenshot_1569876678
Screenshot_1569876695

**Comment by mahmed0715** [comment]
I will work on this next. Looks interesting to me.

**Comment by mahmed0715** [comment]
@sagararyal what should I do with these designs, please let us know

**Comment by harshvitra** [comment]
@sagararyal @norbertschuler 

We can close this and delete it. 

I have taken the code which was needed and  new donations is available in #1908

**Comment by norbertschuler** [comment]
I vote to close this.

**Comment by harshvitra** [comment]
@sagararyal closing this

**Pull request closed without merging**
