### PR TITLE
feature/private_label_leaderboard

### LINKED ISSUE #1959: Show Private Label for Leaderboard entries with maypublish = false
In Leaderboard,
If someone tries to open a profile for a `user without a slug` or user who has `maypublish=false`

Show the following label:
Screen Shot 2020-02-15 at 8 58 17 PM

Note that, label `should not show` initially when the leaderboard tab is loaded.

https://zpl.io/V4dLEEJ

### PR DESCRIPTION
**Pull request by haideralishah**
Fixes #1959

Changes in this pull request:
-Private labels are now clickable.

@sagararyal

### CODE REVIEW

**Comment by sagararyal** [comment]
Please merge develop in this

**Comment by harshvitra** [comment]
@haideralishah can we make this PR ready for review ? 
Remove it from Draft

**Comment by harshvitra** [comment]
Screenshot_2020-02-23-21-00-46-140_org pftp

> Note that, label should not show initially when the leaderboard tab is loaded; and only show when user tries to tap/click on the profile card.

Tested this, works as defined

**Comment by norbertschuler** [comment]
> @haideralishah can we make this PR ready for review ?
> Remove it from Draft

I would assume @haideralishah should be able to click the button "Ready for review". If not, I can do it, but I would prefer the author of the PR to do it.

**Pull request merged**
