### PR TITLE
Fix gift tree skip project selection issue

### PR DESCRIPTION
**Pull request by mahmed0715**
This is urgent issue fix: On gift tree sometimes when we dont provide message it skips project seletion tabs.
@sagararyal Please check if fixed.

### CODE REVIEW

**Comment by mahmed0715** [comment]
Fix https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1521

**Comment by mahmed0715** [comment]
Fix https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1216

**Comment by norbertschuler** [comment]
I‘d like to ask if anyone still knows the original purpose of the `showSelectProject: false` attribute. Someone must have build this with an ideal in his mind?

**Comment by sagararyal** [comment]
works as expected.

**Comment by mahmed0715** [comment]
Fix https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1521

**Pull request merged**
