### PR TITLE
Feature/headers

### PR DESCRIPTION
**Pull request by harshvitra**
Changes Headers across these pages - 

1. Information Page
2. Imprint Page
3. Data Protection Page
4. Target Page
5. Dedicate Trees Page
6. Edit Profile Page
7. Challenge Page
8. Add Competition
9. Create Competition

### CODE REVIEW

**Comment by norbertschuler** [comment]
- [ ] On some screens the header is overlapping the text on my iPhone 11 simulator:

1. Information Page
2. Data Protection Page
3. Dedicate Trees Page (view and edit page)

about
privacy
dedicate_trees
dedicate_trees_2

**Comment by norbertschuler** [comment]
- [ ] I would like to know why on some screens the title is directly written behind the back arrow, while on others it is written in the next line, e.g. on the following screens?

edit_profile
challenge_friend

**Comment by norbertschuler** [comment]
- [ ] I want to suggest some more padding between the title and the and form on this screen:

update_target

**Comment by harshvitra** [comment]
Do not merge, I will fix headers of Add Competition and Edit Competition screens too

**Comment by harshvitra** [comment]
> @harshvitra @sagararyal Now you have completely removed the title from the **edit profile** and **challenge friend** screens. If that's what was wanted I approve this issue?
> 
> Simulator Screen Shot - iPhone 11 - 2020-02-21 at 09 41 05

I forgot to check iOS , Thank you, now this is fixed

**Comment by norbertschuler** [comment]
Please fix eslint errors.

**Comment by norbertschuler** [comment]
@harshvitra I you want you can merge this. I assume the remaining screens will be adapted in the future like the following:

- view competition screen
- all the donation process screens
- all the registration process screens (register, activate, password forgotten et al)

That's a good opportunity to learn what other screens may still exists in the app which we have not changed ;-)

**Comment by harshvitra** [comment]
> * view competition screen
> * all the donation process screens
> * all the registration process screens (register, activate, password forgotten et al)
> * other?

These pages have different headers 
which are under construction.

**Comment by norbertschuler** [comment]
Ok, then I merge this.

**Pull request merged**
