### PR TITLE
Feature/design issues

### LINKED ISSUE #1906: Design issues on "Me", "Redeem", "Leaderboard" screen
I got three design issues (not all related to this PR on my Huawei Honor 6, Android 6, 1024x1980 screen):

- [x] very much whitespace on "Me" screen between avatar and tree counter:

Screenshot_2020-02-05-22-37-56

- [x] quite a lot whitespace on "Redeem" screen:

Screenshot_2020-02-05-22-39-47

- [x] third tab item is cut for "Leaderboard":

Screenshot_2020-02-05-22-33-54

**Smartphone (please complete the following information):**
- Device: Huawei Honor 6
 - OS: Android 6
 - Plant-for-the-Planet App Version 1.3.0

### PR DESCRIPTION
**Pull request by harshvitra**
Fixes 1st and 2nd on this #1940
Fixes #1906

3rd one seems to be already fixed

### CODE REVIEW

**Comment by harshvitra** [comment]
Also fixes 1st and 2nd on this #1906 

Can't replicate 4th

**Comment by norbertschuler** [comment]
> Can't replicate 4th

I activated a pledge event today on https://test.trilliontreecampaign.org/ so you can test this and added two actual screen shots in the issue https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1906#issuecomment-599043203

**Comment by norbertschuler** [comment]
> 3rd one seems to be already fixed

I tested again and could reproduce the bug. Here is a actual screen shot in the issue: https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1940#issuecomment-599042628

**Comment by norbertschuler** [comment]
@harshvitra Can't we set the background to white in general? If not there are still some screens using grey e.g.
- Password forgotten
- User contributions (opening from "Me" screen)
- Register tree (you can only see it some grey in the headline and subtext)

**Comment by harshvitra** [comment]
> * do some more design fixes for pledges

I have other PR for this one https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1872
Will work on it

**Pull request merged**
