### PR TITLE
Added eye option in Login

### PR DESCRIPTION
**Pull request by harshvitra**
Show hide password

And also some changes in UI

Screenshot_2019-12-19-06-04-07-266_org pftp
Screenshot_2019-12-19-06-04-22-765_org pftp
Screenshot_2019-12-19-06-04-42-576_org pftp

@sanjayradadiya the function isn't helping in client validation, please let me know if I'm making a mistake

### CODE REVIEW

**Comment by sanjayradadiya** [comment]
Some flickering issue in ios please check it
https://www.loom.com/share/45774e880a1f41aea1dae2a23c734cc4

**Comment by sanjayradadiya** [comment]
Not able scroll on Android https://www.loom.com/share/11c629d7c7ef4226ad8fc39c929c4512

**Comment by sanjayradadiya** [comment]
some glitching on IOS devices https://www.loom.com/share/45774e880a1f41aea1dae2a23c734cc4

**Comment by harshvitra** [comment]
> Some flickering issue in ios please check it
> https://www.loom.com/share/45774e880a1f41aea1dae2a23c734cc4

Try switching on the soft keyboard

**Pull request merged**
