### PR TITLE
Ready to review : Api change : project api replacing loadtpo api

### LINKED ISSUE #1805: Donate button missing if searching a TPO from a treecounter of another TPO
**Describe the bug**

In the web client looking at the tree counter of a TPO, e.g. https://www.trilliontreecampaign.org/t/plant-for-the-planet, and then searching another TPO, e.g. "Eden" shows the project of this TPO but the "donate" button is missing.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/t/plant-for-the-planet
2. Search for "Eden" and select another TPO
3. See missing button for project

**Expected behavior**
Always show the donate button.

**Screenshots**
Bildschirmfoto 2020-01-10 um 16 10 07

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser: latest Chrome
 - Plant-for-the-Planet App Version 1.1.1

### PR DESCRIPTION
**Pull request by mahmed0715**
Fix https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1681 
Fix https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1765
Fix #1805 
TODO

- [x] Add rating to API List for Featured/ All Projects (@jmiridis) and integrate accordingly in client.

- [x] Clicking All tab doesn't load all projects

- [x] The app is making unnecessary API calls, when being loaded.

Only load the projects when the page that needs project is being loaded.
Screen Shot 2020-01-03 at 10 11 35 PM

- [x] Merge Develop into this branch [ please do not override the UI changes made by Harsh in PlantProjectFull pages]

- [x] fix the names for tax deductible countries
Screen Shot 2020-01-03 at 10 25 46 PM

------------

@jmiridis @sagararyal this is beginning of new api implementation.
loadtpo will be dead after this pr gets merged.

### CODE REVIEW

**Comment by norbertschuler** [comment]
Would be nice if you could create this pull request as a draft instead writing draft in the subject.

**Comment by mahmed0715** [comment]
Fixed the the issues, 
now we load data only when needed,
web: on project selection page, we load the featured projects(with details because we need to show the project carousel), and list of all projects(not with details, we load details on click on the see more in the bottom project list)
2. mobile: only load featured and all on the project selection page, we load  details only when user goes to a details view of the project. 

we already have gross rating for a project in api in list.

**Comment by norbertschuler** [comment]
This change is tricky as the software somehow relied on having all the TPO data for all sort of pages. I found some issues testing against the production backend:

- [ ] In the web client in the carrousel the first and second entry is both "Yucatán Reforestation".

These are the API calls triggers in the web client when opening the projects:
Bildschirmfoto 2020-01-10 um 15 56 21 (I hope our server doesn't fail for the additional load, but maybe these API cost less then the big loadTpo API call before.)

- [ ] In the iOS app I cannot open a project for a TPO if I opened it from the tree counter of the TPO (which I opened before through the search). I have not opened the projects before and get a blank page:

Simulator Screen Shot - iPhone 11 - 2020-01-10 at 16 16 58

- [ ] If I have loaded the projects before in my iOS app and then try to open a project from the tree counter page of an TPO the behavior is different and I get a crash instead:
```
TypeError: undefined is not an object (evaluating 'paymentSetup.taxDeduction')

This error is located at:
    in PlantProjectSnippetDetails (created by ConnectFunction)
ushedQueue
    [native code]:0

```

**Comment by mahmed0715** [comment]
Looks like this PR needs a whole app checkup, Thanks @norbertschuler , I am checking on these.. This is true I know this can happen on many places 
I will fix these errors asap..

**Comment by mahmed0715** [comment]
@sagararyal @norbertschuler there is an issue https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1681 which is fixed in this PR.

**Comment by mahmed0715** [comment]
@sagararyal please check if api issue fixed with project list...

**Comment by mahmed0715** [comment]
> * In the web client in the carrousel the first and second entry is both "Yucatán Reforestation".

We did a trick to fix a production issue , actually the Yucatan project is the first one and last one.

**Comment by mahmed0715** [comment]
@sagararyal all the issues are fixed now
fixed leaf option on project details(verified self reported)
fixed image description view and other issues related to the public tree counter..

**Comment by mahmed0715** [comment]
@norbertschuler the issues are fixed now I think

**Comment by norbertschuler** [comment]
I have not yet approved this as I had no time to do a bigger test of the app and web client with this change. Maybe someone else can do it. Also this branch has been merged into `origin/feature/leaderboard_refresh` (see https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1803), but not completely, but only until the commit https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1803/commits/c770f5b03cd6b12b531fc818377e04b70ca6ea6d by @haideralishah.

**Comment by mahmed0715** [comment]
@sagararyal the issue with project in public tree counter transition between proects fixed,
Video thumbnail zoom now added, please check this ..

**Comment by mahmed0715** [comment]
@sagararyal @norbertschuler please check this PR and I hope it gets merged asap..
@harshvitra @sanjayradadiya also please review this PR..

**Pull request merged**
