### PR TITLE
Feature/new splash screen

### LINKED ISSUE #2278: Change loading Screen
On Native Apps,
Please change the Trillion Tree Campaign Page (that loads when the app comes from sleep, or initial load)
IMG_5D589738395B-1

to

Screen Shot 2020-05-04 at 10 54 27 PM

Design is available in Adobe XD (please use vector icons)

### PR DESCRIPTION
**Pull request by harshvitra**
Fixes #2278 

@sagararyal please check

### CODE REVIEW

**Comment by norbertschuler** [comment]
iPhone 11 Pro on Browserstack:

Bildschirmfoto 2020-05-05 um 18 31 40

Galaxy S20 on Browserstack - where is the UN logo?

Bildschirmfoto 2020-05-05 um 18 25 22

Probably this does not support any translations of text resources, does it?

**Comment by sagararyal** [comment]
Screen Shot 2020-05-11 at 4 04 32 PM
@harshvitra  Same issue on Pixel 4; seems android related.

I don't think localization is necessary.

**Comment by sagararyal** [comment]
Screen Shot 2020-05-11 at 4 06 33 PM

Can we color that part as well.

**Comment by harshvitra** [comment]
@sagararyal @norbertschuler 

This is what happens when I import SVG for drawable. It skips the logo because it has <pattern> wrapper. 

Screenshot 2020-05-12 at 12 39 42 PM

Screenshot 2020-05-12 at 12 39 50 PM

Tried the options here and other stackoverflow links

https://medium.com/@kaushcode/android-working-with-vectordrawable-can-we-easily-convert-svg-to-vectordrawable-e4000143b13f

Can some one from native background advice ? Or can we change the design @sagararyal in some way that it doesn't have the <pattern> wrapper.

**Comment by norbertschuler** [comment]
> @sagararyal @norbertschuler
> 
> This is what happens when I import SVG for drawable. It skips the logo because it has wrapper.

Sorry, I don't know how to access Adobe XD to get the SVG file.

**Comment by norbertschuler** [comment]
Anyone else having the problem that on the iPhone 11 simulator the new Splash screen does not shows correctly?

Simulator Screen Shot - iPhone 11 - 2020-05-12 at 20 30 28

**Comment by norbertschuler** [comment]
Please check if https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2346 could replace this?

**Comment by norbertschuler** [comment]
I understood now the big advantage of `react-native-splash-screen` is the longer time the splash screen is showing. So I added the optimizations from here too and vote to use this patch.

**Comment by norbertschuler** [comment]
@sagararyal please review and merge if you like it. (I wasn't able to use fullscreen mode for the Android Splash screen.)

**Pull request merged**
