### PR TITLE
Add share to single projects

### PR DESCRIPTION
**Pull request by niteshgrg**

### CODE REVIEW

**Comment by norbertschuler** [comment]
This is what I changed to have a share link for the project list: https://github.com/Plant-for-the-Planet-org/treecounter-app/commit/dfaf31c1677b88ed7ec171967e5d8c283c395bfc

**Comment by sagararyal** [comment]
I want the share link on pages like this:

Screenshot_20190827-110006_Plant

**Comment by norbertschuler** [comment]
The patch is putting a share link on this page, but it’s just a static link https://www.trilliontreecampaign.org/select-project

**Comment by norbertschuler** [comment]
We should either work on this issue or discard the pull request.

**Comment by sagararyal** [comment]
@niteshgrg any update on this?

**Comment by niteshgrg** [comment]
@sagararyal no occupied with the payments task.

**Comment by norbertschuler** [comment]
closing this by now (the one line change of code is easy to be done again) in favor to this issue https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1381

**Pull request closed without merging**
