### PR TITLE
Fix android issue on Login Page

### LINKED ISSUE #1809: Login field design broken on data input
**Describe the bug**
When entering the E-Mail or password in the new login form, the input area overlaps with the title text and the layout is broken.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to Login View
2. Click on Input field for E-mail and/or password
3. See error

**Expected behavior**
Show a correct layout.

**What actually happens**
The input area of the email or password field is overlapping with each other and the label area.

**Screenshots**
1. Entering E-Mail:

Screenshot_1578921950

2. Entering password:

Screenshot_1578921973

**Smartphone (please complete the following information):**
- Device: Android emulator
 - OS: Android 8.1.0
 - Plant-for-the-Planet App Version 1.1.1

### PR DESCRIPTION
**Pull request by harshvitra**
Fixes #1809 

@norbertschuler Please test

### CODE REVIEW

**Comment by norbertschuler** [comment]
I tested again and it does not yet work for me - @harshvitra do you have an Android device to test with yourself?

Screenshot_1578988818
Screenshot_1578988829

**Comment by norbertschuler** [comment]
I also tested the new login page now on an iPhone 5s and it also does not work with that small screen - @harshvitra @sagararyal I think the current version of the login page just does not work with small screens and should be build again from scratch:

Simulator Screen Shot - iPhone 5s - 2020-01-14 at 09 23 13
Simulator Screen Shot - iPhone 5s - 2020-01-14 at 09 22 59
Simulator Screen Shot - iPhone 5s - 2020-01-14 at 09 22 45

**Comment by harshvitra** [comment]
Quickest fix to this reverting KeyboardAvoidingView - Purpose of this is to make the LOGIN button appear on top of Keyboard

**Comment by sagararyal** [comment]
@harsh you can disable keyboard avoiding view. but is it possible to rename the button in keyboard to Next, and Login when fields are filled?

**Comment by norbertschuler** [comment]
> Quickest fix to this reverting KeyboardAvoidingView - Purpose of this is to make the LOGIN button appear on top of Keyboard

I already tested to remove KeyboardAvoidingView, but still got problems. Please proof me wrong and create a solution without problems for small screens on iOS & Android :-)

**Comment by harshvitra** [comment]
> I already tested to remove KeyboardAvoidingView, but still got problems. Please proof me wrong and create a solution without problems for small screens on iOS & Android :-)

Test now @norbertschuler

**Comment by harshvitra** [comment]
> @harsh you can disable keyboard avoiding view. but is it possible to rename the button in keyboard to Next, and Login when fields are filled?

returnKeyLabel is the parameter, but it only is only for Android 

Currently using returnkeyType - 
Email - type is next
Password - type is done

**Comment by norbertschuler** [comment]
> > @harsh you can disable keyboard avoiding view. but is it possible to rename the button in keyboard to Next, and Login when fields are filled?
> 
> returnKeyLabel is the parameter, but it only is only for Android
> 
> Currently using returnkeyType -
> Email - type is next
> Password - type is done

Got two issues:
- [ ] Input field for email on iPhone5s got hidden so you can not see if you want to enter data.
- [ ] The password field on Android does not allow to close the keyboard, so you can not submit the form as the button is hidden.

**Comment by harshvitra** [comment]
> * [ ]  Input field for email on iPhone5s got hidden so you can not see it if you want to enter data.

Is it worth to focus for iphone ? https://david-smith.org/iosversionstats/

**Comment by norbertschuler** [comment]
> > * [ ]   Input field for email on iPhone5s got hidden so you can not see it if you want to enter data.
> 
> Is it worth to focus for iphone5s ? https://david-smith.org/iosversionstats/

Well, Android is more important. Got about 0,2% of our users reporting errors with it on Bugsnag, but that could have been me :-)

**Pull request merged**
