### PR TITLE
Fb/ndvi

### PR DESCRIPTION
**Pull request by hkurra**
Implemented on both mobile and Web
On mobile, it has been integrated on Plant project and User contribution but on the web only on plant project,
Currently, NDVI root container component fetching data from API only if it has valid NDVI UID, if api return something then it will show that information in UI else it will show hard-coded information for now.
To remove this hardcoded behavior just remove some code from error handler under container/NDVI/NDVI.js 

image

image
image

### CODE REVIEW

**Comment by norbertschuler** [comment]
The date is shown as “July,2019”. I would expect “July, 2019” with a space behind the “,” or it looks wrong.

**Comment by norbertschuler** [comment]
Please note this pull requests needs an `npm install` in order to work.

**Comment by norbertschuler** [comment]
I just tested it on the TTC test backend and got an error when clicking on our first project:
Simulator Screen Shot - iPhone X - 2019-07-21 at 11 34 54

This was requested from the server:
https://test.trilliontreecampaign.org/public/v1.1/de/ndvi/na_RZQPwavkM60WK29AOr

This is the error:
```
TypeError: undefined is not an object (evaluating 'this.state.selectedDataPoint.carbon')

This error is located at:
    in NDVIContainer (at NDVI.js:53)
    in NDVIContainer (at PlantProjectDetails.native.js:49)
    in RCTView (at View.js:45)
    in View (at PlantProjectDetails.native.js:28)
    in PlantProjectDetails (at PlantProjectFull.native.js:71)
    in RCTView (at View.js:45)
    in View (at PlantProjectFull.native.js:70)
    in RCTView (at View.js:45)
    in View (at TouchableItem.native.js:33)
    in TouchableItem (at Card/index.native.js:8)
    in CardLayout (at PlantProjectFull.native.js:57)
    in RCTScrollContentView (at ScrollView.js:976)
    in RCTScrollView (at ScrollView.js:1115)
    in ScrollView (at PlantProjectFull.native.js:51)
    in RCTView (at View.js:45)
    in View (at PlantProjectFull.native.js:50)
    in PlantProjectFull (at SelectedPlantProject/index.js:44)
    in SelectedPlantProjectContainer (created by Connect(SelectedPlantProjectContainer))
    in Connect(SelectedPlantProjectContainer) (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.js:400)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:45)
    in View (at Transitioner.js:141)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at DrawerView.js:87)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (created by DrawerLayout)
    in RCTView (at View.js:45)
    in View (created by DrawerLayout)
    in DrawerLayout (at DrawerView.js:84)
    in DrawerView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at AppDrawerNavigatorContainer.js:101)
    in RCTView (at View.js:45)
    in View (at AppDrawerNavigatorContainer.js:100)
    in AppDrawerNavigatorContainer (created by Connect(AppDrawerNavigatorContainer))
    in Connect(AppDrawerNavigatorContainer) (at TreeCounter.native.js:26)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-safe-area-view/index.js:134)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at TreeCounter.native.js:22)
    in App (created by Connect(App))
    in Connect(App) (at App/index.js:20)
    in GlobalErrorBoundary (at App/index.js:19)
    in Provider (at App/index.js:18)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at react-native-root-siblings/index.js:34)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

render
    index.bundle?platform=ios&dev=true&minify=false:209459:52
finishClassComponent
    index.bundle?platform=ios&dev=true&minify=false:19643:43
updateClassComponent
    index.bundle?platform=ios&dev=true&minify=false:19606:50
performUnitOfWork
    index.bundle?platform=ios&dev=true&minify=false:23763:27
workLoop
    index.bundle?platform=ios&dev=true&minify=false:23797:47
renderRoot
    index.bundle?platform=ios&dev=true&minify=false:23863:21
performWorkOnRoot
    index.bundle?platform=ios&dev=true&minify=false:24601:23
performWork
    index.bundle?platform=ios&dev=true&minify=false:24528:30
performSyncWork
    index.bundle?platform=ios&dev=true&minify=false:24504:20
requestWork
    index.bundle?platform=ios&dev=true&minify=false:24402:26
scheduleWork
    index.bundle?platform=ios&dev=true&minify=false:24275:22
enqueueSetState
    index.bundle?platform=ios&dev=true&minify=false:16528:23
setState
    index.bundle?platform=ios&dev=true&minify=false:7825:37
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:209158:27
tryCallOne
    index.bundle?platform=ios&dev=true&minify=false:3771:16
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:3872:27
_callTimer
    index.bundle?platform=ios&dev=true&minify=false:27802:17
_callImmediatesPass
    index.bundle?platform=ios&dev=true&minify=false:27838:19
callImmediates
    index.bundle?platform=ios&dev=true&minify=false:28057:33
callImmediates
    [native code]:0
__callImmediates
    index.bundle?platform=ios&dev=true&minify=false:3173:35
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:2994:34
__guard
    index.bundle?platform=ios&dev=true&minify=false:3156:15
flushedQueue
    index.bundle?platform=ios&dev=true&minify=false:2993:21
flushedQueue
    [native code]:0
callFunctionReturnFlushedQueue
    [native code]:0
```

**Comment by norbertschuler** [comment]
I tested on TTC test backend with the web client now for the same project and first received this view now
- where the resource `label.NDVI_tooltip_for_help_button` is not yet having an English text
- the ?-button for help does not open any tooltip for me when clicking on it
- clicking the refresh-button trigger the API call, but results into a stack trace as following:

```
bugsnag.js:2031 Warning: Failed prop type: Invalid prop `dataPoints` of type `object` supplied to `NDVI`, expected `array`.
    in NDVI (created by NDVIContainer)
    in NDVIContainer (created by PlantProjectDetails)
    in div (created by PlantProjectDetails)
    in div (created by PlantProjectDetails)
    in PlantProjectDetails (created by PlantProjectFull)
    in PlantProjectFull (created by SelectPlantProject)
    in div (created by CardLayout)
    in CardLayout (created by SelectPlantProject)
    in div (created by Slider)
    in div (created by Slider)
    in div (created by Track)
    in Track (created by InnerSlider)
    in div (created by InnerSlider)
    in div (created by InnerSlider)
    in InnerSlider (created by Slider)
    in Slider (created by SelectPlantProject)
    in div (created by SelectPlantProject)
    in div (created by SelectPlantProject)
    in SelectPlantProject (created by SelectPlantProjectContainer)
    in SelectPlantProjectContainer (created by Connect(SelectPlantProjectContainer))
    in Connect(SelectPlantProjectContainer) (created by DonateTrees)
    in DonateTrees (created by DonationTreesContainer)
    in DonationTreesContainer (created by Connect(DonationTreesContainer))
    in Connect(DonationTreesContainer) (created by Route)
    in Route (created by TreeCounter)
    in Switch (created by TreeCounter)
    in BodyErrorBoundary (created by Route)
    in Route (created by withRouter(BodyErrorBoundary))
    in withRouter(BodyErrorBoundary) (created by TreeCounter)
    in div (created by TreeCounter)
    in div (created by TreeCounter)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by TreeCounter)
    in div (created by TreeCounter)
    in TreeCounter (created by Connect(TreeCounter))
    in Connect(TreeCounter) (created by App)
    in GlobalErrorBoundary (created by App)
    in Provider (created by App)
    in App
```
Bildschirmfoto 2019-07-21 um 11 43 19

Maybe just the same problem with the API response.

**Comment by norbertschuler** [comment]
Which backend can I use for testing the feature?

**Comment by hkurra** [comment]
I will test this with production backend first to see if it working or not as expected

**Comment by norbertschuler** [comment]
> I will test this with production backend first to see if it working or not as expected

I have tested production and test backend, but both still failed with above errors. Does it work for you?

**Comment by norbertschuler** [comment]
@hkurra I really would like to review this pull request, but I as you can see above I can not test it with the current production or test backend - can you?

Bildschirmfoto 2019-07-27 um 10 32 43

**Comment by hkurra** [comment]
@norbertschuler i have fixed the issue, you can test on production DB, it should work now 
regarding Tooltip Issue, we have added placeholder under NDVI.json please update them as per the requirements after consulting with @sagararyal 
image

**Comment by norbertschuler** [comment]
First time I could see something - made this screenshot on iOS:
- two translations are missing that I marked: 
(1) NDVI_carbon_title will be translated once the patch is merged, but (2) "October" does not seem to be a resource and should somehow be localized (the month name gets correctly translated once you click on one of the month above to update the data below - the error happens only the first time the page got loaded
- nothing happens when clicking the question marks, should it?

Simulator Screen Shot - iPhone X - 2019-08-01 at 15 10 41

**Comment by norbertschuler** [comment]
The first time it is loaded in the web client the layout is cut - corrected when I resize the browser window:

Bildschirmfoto 2019-08-01 um 15 35 57
Bildschirmfoto 2019-08-01 um 15 36 35

**Comment by norbertschuler** [comment]
Values for Min, Avg and Max should be rounded mathematically, e.g. two digits behind the dot (0,65544566 -> 0.66)

**Comment by norbertschuler** [comment]
In my iOS simulator clicking on the circles for the data of different month does not update the below data any more. It only works in the web client. Trying it on my Android emulator crashes with the following message:
```
Error while updating property 'colors' of a view managed by: BVLinearGradient

null

needs >= 2 number of colors
updateViewProp
    ViewManagersPropertyCache.java:95
setProperty
    ViewManagerPropertyUpdater.java:132
updateProps
    ViewManagerPropertyUpdater.java:51
updateProperties
    ViewManager.java:37
createView
    NativeViewHierarchyManager.java:265
execute
    UIViewOperationQueue.java:200
dispatchPendingNonBatchedOperations
    UIViewOperationQueue.java:1109
doFrameGuarded
    UIViewOperationQueue.java:1080
doFrame
    GuardedFrameCallback.java:29
doFrame
    ReactChoreographer.java:166
doFrame
    ChoreographerCompat.java:84
run
    Choreographer.java:947
doCallbacks
    Choreographer.java:761
doFrame
    Choreographer.java:693
run
    Choreographer.java:935
handleCallback
    Handler.java:873
dispatchMessage
    Handler.java:99
loop
    Looper.java:193
main
    ActivityThread.java:6669
invoke
    Method.java
run
    RuntimeInit.java:493
main
    ZygoteInit.java:858

```

**Comment by norbertschuler** [comment]
@hkurra Great improvement. Not fixed from my reported issues are:
- In the iOS and Android app "October, 2015" is not translated on first view - but when you click a data point it gets replaced with correctly translated month names.
- Values for Min, Avg and Max should be rounded mathematically, e.g. two digits behind the dot (0,65544566 -> 0.66) - otherwise the layout looks very ugly.

@sagararyal as these two points are no real stopper, I would merge this pull request and create another one labelled "enhancement" with above issues. Keep in mind you cannot do a release before the new resources got translated in the `develop`-branch.

**Comment by sagararyal** [comment]
Looks good, I saw in lingo hub that Months are being rendered as below

that should change.

Months should be `months`,

`January`
February...
and extract first letter when on small devices and extract 3 letters when the component is on wide screen responsive as here: https://zpl.io/V1QWnPm


Screen Shot 2019-08-02 at 12 11 39 PM

**Pull request merged**
