### PR TITLE
[WIP]: Auth0 SSO sign up and login

### PR DESCRIPTION
**Pull request by crucialfelix**
Working:

- Sign up or login using Auth0 (with various identity providers)
- App creates a userProfile (name, email, picture) and you are logged in
- Authenticated requests to our backend use Auth0 JWT

Not yet:
- [ ] Backend does not yet recognize the Auth0 JWT so you can't do any user actions
- [ ] Select user type: individual / organization and fill out extra info
- [ ] react-native

### CODE REVIEW

**Comment by crucialfelix** [comment]
I don't get any lint errors locally. 

This is the reason eslint it exited with non-0 status:

```
<testsuite package="org.eslint" time="0" tests="1" errors="1" name="/home/circleci/ttc-app/app/config/index.js">
<testcase time="0" name="org.eslint.unknown" classname="/home/circleci/ttc-app/app/config/index"><error message="Parsing error: Unexpected token&#10;&#10;&#27;[0m &#27;[90m 23 | &#27;[39m  auth0clientId&#27;[33m:&#27;[39m &#27;[32m&apos;&apos;&#27;[39m&#27;[0m&#10;&#27;[0m &#27;[90m 24 | &#27;[39m}&#27;[0m&#10;&#27;[0m&#27;[31m&#27;[1m&gt;&#27;[22m&#27;[39m&#27;[90m 25 | &#27;[39m}&#27;[33m;&#27;[39m&#27;[0m&#10;&#27;[0m &#27;[90m    | &#27;[39m&#27;[31m&#27;[1m^&#27;[22m&#27;[39m&#27;[0m&#10;&#27;[0m &#27;[90m 26 | &#27;[39m&#27;[0m"><![CDATA[line 25, col 1, Error - Parsing error: Unexpected token&#10;&#10;&#27;[0m &#27;[90m 23 | &#27;[39m  auth0clientId&#27;[33m:&#27;[39m &#27;[32m&apos;&apos;&#27;[39m&#27;[0m&#10;&#27;[0m &#27;[90m 24 | &#27;[39m}&#27;[0m&#10;&#27;[0m&#27;[31m&#27;[1m&gt;&#27;[22m&#27;[39m&#27;[90m 25 | &#27;[39m}&#27;[33m;&#27;[39m&#27;[0m&#10;&#27;[0m &#27;[90m    | &#27;[39m&#27;[31m&#27;[1m^&#27;[22m&#27;[39m&#27;[0m&#10;&#27;[0m &#27;[90m 26 | &#27;[39m&#27;[0m]]></error></testcase>
</testsuite>
```

**Comment by jmiridis** [comment]
Which backend are you running this against? Staging?

**Comment by crucialfelix** [comment]
It runs against test (I'm on local dev). You can probably see me pestering your server with foreign JWTs.

**Comment by crucialfelix** [comment]
@norbertschuler I think the lint failure has to do with config/index.js

rrors="1" name="/home/circleci/ttc-app/app/config/index.js

```

[0m [90m 23 | [39m  auth0clientId[33m:[39m [32m''[39m[0m
[0m [90m 24 | [39m}[0m
[0m[31m[1m>[22m[39m[90m 25 | [39m}[33m;[39m[0m
[0m [90m    | [39m[31m[1m^[22m[39m[0m
[0m [90m 26 | [39m[0m"><![CDATA[line 25, col 1, Error - Parsing error: Unexpected token

[0m [90m 23 | [39m  auth0clientId[33m:[39m [32m''[39m[0m
[0m [90m 24 | [39m}[0m
[0m[31m[1m>[22m[39m[90m 25 | [39m}[33m;[39m[0m
[0m [90m    | [39m[31m[1m^[22m[39m[0m
[0m [90m 26 | [39m[0m]]
```
It is probably because we need to add values to the generated config/index.js:

```
  auth0domain: 'planetapp.eu.auth0.com',
  auth0clientId: ''
```

Where is that generated?

**Comment by norbertschuler** [comment]
I just think the config/index.js has a syntax error for having two closing } at the end: 
```
  auth0domain: 'https://accounts.plant-for-the-planet.org',
  auth0clientId: ''
}
};
```
It seems to me the output from eslint with the color code is not compatible with the XML format it produces, so the XML file is not valid any more. Can we suppress using ANSI color code in the output of eslint?

**Comment by crucialfelix** [comment]
The formatting is like that because it's making an XML file for circle ci to display pretty error results. It's not meant for human consumption.

Thanks for spotting the problem!

**Comment by norbertschuler** [comment]
@crucialfelix wrote in https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/2358#issuecomment-629604791 "The branch I did has long since expired".

**Comment by crucialfelix** [comment]
But don't delete it. Use it as a reference.  The way the user is accessible from any component is important.

**Comment by norbertschuler** [comment]
> But don't delete it. Use it as a reference. The way the user is accessible from any component is important.

I won't delete the branch, just thinking about closing the pull request - but maybe it's easier to look at the code in GitHub than locally, what do you think ? It's just I like to have to clean list of pull requests ;-)

**Comment by norbertschuler** [comment]
As we already implemented Auth0 now in the new website, I am closing this.

**Pull request closed without merging**
