### PR TITLE
Fix currency selector style fix so that it shows always on screen

### LINKED ISSUE #1564: Make the language/currency selector always visible.
From @sagararyal 
The language/currency selector currently on small screen is hidden(at the bottom of the left menu item).
We need to make that part always visible even if we need to overlap the menu items.

Suggestions appreciated how to manage the menu and this selector on small screen.

### PR DESCRIPTION
**Pull request by mahmed0715**
@sagararyal Please check this is what you wanted?

Fix #1564

### CODE REVIEW

**Comment by mahmed0715** [comment]
Fix https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1564

**Comment by sagararyal** [comment]
Screen Shot 2019-10-28 at 7 10 40 PM

In safari the content is missing.

**Comment by mahmed0715** [comment]
> Screen Shot 2019-10-28 at 7 10 40 PM
> 
> In safari the content is missing.
> @mahmed0715

I suspect the css changes are missing in your system, Can you please do a clear cache first before you check again please.. @sagararyal sometimes that happens to us as well...

**Comment by mahmed0715** [comment]
@norbertschuler it looks okay now on safari as well.. Merging..

**Comment by norbertschuler** [comment]
@mahmed0715 also if you do not write this patch for the native app, though it's sharing code with the web client and currently is crashing when you try to do a donation (I assume it's crashing in the `convertCurrency()` method):
```
TypeError: undefined is not an object (evaluating 'currencies.rates[fromCurrency]')

This error is located at:
    in TreeCountSelector (at TreeCountCurrencySelector.native.js:163)
    in RCTView (at View.js:45)
    in View (at TreeCountCurrencySelector.native.js:162)
    in RCTView (at View.js:45)
    in View (at TouchableItem.native.js:33)
    in TouchableItem (at Card/index.native.js:7)
    in CardLayout (at TreeCountCurrencySelector.native.js:88)
    in RCTScrollContentView (at ScrollView.js:976)
    in RCTScrollView (at ScrollView.js:1115)
    in ScrollView (at KeyboardAwareHOC.js:509)
    in KeyboardAwareScrollView (at TreeCountCurrencySelector.native.js:84)
    in TreeCountCurrencySelector (at DonateTrees/index.native.js:289)

convertCurrency
    index.bundle?platform=ios&dev=true&minify=false:169292:47
getSingleTreeRate
    index.bundle?platform=ios&dev=true&minify=false:190380:46
calculateAmount
    index.bundle?platform=ios&dev=true&minify=false:190370:61
proxiedMethod
    [native code]:0
TreeCountSelector
    index.bundle?platform=ios&dev=true&minify=false:191483:48
TreeCountSelector
    [native code]:0```

**Comment by mahmed0715** [comment]
this is in this branch? you sure. because this branch is related to only some css change. may be you were referring to othere PR https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1572 ? @norbertschuler

**Comment by norbertschuler** [comment]
> this is in this branch? you sure. because this branch is related to only some css change. may be you were referring to othere PR #1572 ? @norbertschuler

sorry, wrong PR.

**Pull request merged**
