### PR TITLE
added lint:fix command into package.json and run it

### PR DESCRIPTION
**Pull request by norbertschuler**
I added `eslint app --fix` as a command to be run with `npm run lint:fix` manually (not yet automatically) and it just fixes two different things (but a lot of these things):

- changing true attributes like `<TextBlock strong={true}>` to `<TextBlock strong>`
- changing double negation `!!` to nothing

### CODE REVIEW

**Comment by norbertschuler** [comment]
Please let's decide if this is worth merging. At least the number of warning returns from eslint is decreased to 2482 ;-)

**Comment by norbertschuler** [comment]
We have to be aware this refactoring work and patches can disturb the development of other features due to constant merge conflicts.

**Comment by crucialfelix** [comment]
There is also somebody working on fixing those right now. Best not to step on his toes.

https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1333

**Comment by norbertschuler** [comment]
All right, I will discard this.

**Pull request closed without merging**
