### PR TITLE
fix competition and gift user button issue

### LINKED ISSUE #1883: Bottom buttons without padding
On some screens the button at the bottom uses the full horizontal space (probably not using the right style for a button):

Bildschirmfoto 2020-02-03 um 12 06 07

- [ ] create a new competition
- [ ] gift a tree to a user search by his name

Simulator Screen Shot - iPhone 11 - 2020-02-03 at 11 53 22
Simulator Screen Shot - iPhone 11 - 2020-02-03 at 11 53 31

### PR DESCRIPTION
**Pull request by sanjayradadiya**
Fixes #1883

Changes in this pull request:
- fix competition button
- fix gift user button

@sagararyal @norbertschuler

### CODE REVIEW

**Comment by sanjayradadiya** [comment]
image
image

**Comment by norbertschuler** [comment]
Maybe the following issues are not based on this change (I have not yet tested them without this patch), but for trying to gift a tree to a known user by choosing his tree counter on an small Android device I have lot's of problems entering data:

- [ ] the search field is only partially visible:
Screenshot_2020-02-05-12-22-48

- [ ] the field for entering an optional message can not seen at all when entering information:
Screenshot_2020-02-05-12-24-52

- [ ] selecting a tree counter from the search results also is quite difficult without hiding the keyboard manually:
Screenshot_2020-02-05-12-25-23

**Comment by norbertschuler** [comment]
- [ ] the button to create a new challenge has no bottom padding, so directly connected to the black Android navigation elements:

Screenshot_2020-02-05-12-37-08

**Comment by norbertschuler** [comment]
I put the other input issues into an own issue, so we can merge this without fixing them: https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1905

**Comment by sanjayradadiya** [comment]
image

**Pull request merged**
