### PR TITLE
added proper permission management to access the location

### LINKED ISSUE #1423: Geo-Location does not work on iOS to register trees
**Describe the bug**
When I want to register trees I can not get the location of my iPhone. 

**Is it on a Production or Development Build?**
production 

**To Reproduce**
1. Go to 'register trees‘
2. Click on 'get position‘

**Expected behavior**
Get phone location. 

**What actually happens**
Nothing. Not even asking for location permission. 

**Screenshots**
34130D99-D95F-4EFA-8952-40545BE4E447

**Smartphone (please complete the following information):**
- Device: iPhoneX
 - OS: iOS 12.4
 - Plant-for-the-Planet App Version 1.0.7

### PR DESCRIPTION
**Pull request by norbertschuler**
Fix #1423

- Currently iOS does not ask for permission to access the location, but silently fails (can only be activated in the settings to make it work, but nobody tells the user to do that)
- On Android it also already worked before.

### CODE REVIEW

**Comment by norbertschuler** [comment]
In RN 0.60.x the module is extracted into an own module https://github.com/react-native-community/react-native-geolocation and we need to migrate the code to still work.

**Comment by sagararyal** [comment]
@norbertschuler lets not worry about this now, we will have maps soon.

**Comment by norbertschuler** [comment]
@sagararyal so you want me to abandon this pull request?

**Comment by norbertschuler** [comment]
@sagararyal This pull request adds two more native libraries to the Android and iOS project. Therefore you need to update the project with `npm install`. But sometimes I also experience that running `react-native run-ios` afterwards (which is using the Xcode CLI) fails. Then I rebuild the project with Xcode itself and it works well again. (I have to investigate this, maybe the CLI does not really rebuild the iOS app from scratch, but using some cache.)

**Pull request merged**
