### PR TITLE
added basic support for Portuguese (brazil) languages

### LINKED ISSUE #2215: Enable Portuguese (Brazil) Translation in App and Backend
**Enable Portuguese (Brazil) Translation in App and Backend.**
*I had recently given Flavia access to translate into Portuguese and added the Portuguese (Brazil) which she translated to*

**What are the use cases for this feature?**
*Translate the App to Portuguese for our Portuguese speaking users etc.*

**Examples of this feature or functionality.**
*We just had the Spanish translation done and it looks good too*

### PR DESCRIPTION
**Pull request by norbertschuler**
Fixes #2215

This is a first draft for testing on different devices with different languages. I will merge this only if Portuguese translation is >99% done or after I have removed "pt" again and only keep "pt-BR".

To-Do's:
- [x] add country flag for Portugal and Brazil (exact size of format as German and Spanish)
- [x] add Google and Apple AppStore banners (exact size of format as German and Spanish)
- [x] test what happens when Portuguese (Portugal), i.d. `pt-PT` is chosen instead `pt` or `pt-BR` -> `pt-PT` is falling back to `pt`
- [x] copy e-mail templates for `pt-BR` to backend
- [x] deactivated `pt`
- [ ] prepare app stores with resources

@Chiagozie-Udeh

### CODE REVIEW

**Comment by norbertschuler** [comment]
Our web layout breaks for the longer language names for the dropdown:

Bildschirmfoto 2020-05-09 um 21 00 41

**Comment by norbertschuler** [comment]
- To generate a Google PlayStore badge: https://play.google.com/intl/en_us/badges/
- To download Apple AppStore badges: https://developer.apple.com/app-store/marketing/guidelines/

Both have to be adapted to our size of height 100px and dynamic width.

**Comment by norbertschuler** [comment]
Flag can be build from SVG files in treecounter-plattform repository e.g.
- `rsvg-convert -h 512 ../treecounter-platform/public/images/flags/svg/BR.svg -o app/assets/images/flags/brazil.png`
- change the width to 512 pixel and cut a circle of the resulting image
- optionally optimized image with tinypng.com

**Comment by norbertschuler** [comment]
@Chiagozie-Udeh thank you for testing. You’re right, the app demands to be killed and restarted to load another language. Supporting to change the language while running the app demands more work for which I would like to have a new issue.

**Comment by norbertschuler** [comment]
@Chiagozie-Udeh there was a bug not showing "Portuguese (Brazil)" on the native apps, but only "Portuguese (Portugal)" - please test once more.

Bildschirmfoto 2020-05-11 um 10 18 15

**Comment by norbertschuler** [comment]
I will merge this only if Portuguese translation is >99% done or after I have removed "pt" again and only keep "pt-BR".

**Comment by Chiagozie-Udeh** [comment]
Just tested and I could see Portuguese Brazil on the native App for the devices I checked both for Android and iOS

**Comment by norbertschuler** [comment]
> I will merge this only if Portuguese translation is >99% done or after I have removed "pt" again and only keep "pt-BR".

I deactivated `pt` for now in this patch. It can easily be reactivated once Portuguese (Portugal) is translated.

**Comment by sagararyal** [comment]
@norbertschuler I think permission messages still need to be translated; besides that looks good.

**Comment by norbertschuler** [comment]
> @norbertschuler I think permission messages still need to be translated; besides that looks good.

Permission String are already translated, but not yet exported from LingoHub and merged into this PR - we will add them directly to the develop branch: https://translate.lingohub.com/plant-for-the-planet/dashboard/planet-app-(ios-resources)/

**Pull request merged**
