### PR TITLE
Integrate formik forms and implement function for convert form schema

### PR DESCRIPTION
**Pull request by sanjayradadiya**

### CODE REVIEW

**Comment by sagararyal** [comment]
@harshvitra @sanjayradadiya What's pending here?

**Comment by harshvitra** [comment]
@sanjayradadiya 

- [ ] Remove the changes in the pledge form 

- [ ] Keep the function to generate the validation form schema, keep the validation errors file and its reference in locale/en 

- [ ] Add function to generate the initial values. 

@sagararyal  Once this is done we can merge this in develop and use it in other features to update the forms to Formik. 

**The process will be -** 
1. @jmiridis generates forms and gives us the json response 
2. We use [Json to JS](https://json-to-js.com/) in front end to get the schema as js object
3. We use the function to generate validation schema and initial values needed for Formik

@norbertschuler we can make such processes to simplify+organize work

**Comment by norbertschuler** [comment]
> @norbertschuler we can make such processes to simplify+organize work

I guess until now it has to be done manually.

**Comment by harshvitra** [comment]
> > @norbertschuler we can make such processes to simplify+organize work
> 
> I guess until now it has to be done manually.

Even if we have a manual process we can document it and find tools to make it easier

**Comment by norbertschuler** [comment]
For now I put all my documentation in the repository‘s wiki: https://github.com/Plant-for-the-Planet-org/treecounter-app/wiki - would you like to add this new process? Do we already know how it works step by step?

**Comment by Plant-for-the-Planet** [comment]
I guess this can be closed, as we pledge events and competitions will take this pr to develop.

**Comment by norbertschuler** [comment]
so closing this

**Pull request closed without merging**
