### PR TITLE
New UI and new API for project

### PR DESCRIPTION
**Pull request by mahmed0715**
Todos
Test from Dec 27
- [x] on click menu item `Donate` Unrecognized font family OpenSans-RegularItalic

- [ ] Hyperlink TPO Image to TPO Profile (don't make any visible changes)

- [ ] Increase Image quality of TPO Icon.

- [ ] Get video Thumbnail picture, as background of the video box.

- [ ] @mahmed0715 in the Image Preview page, please follow guidelines for iOS SafeArea

---------
to dos,

- [x] fix main page UI, current design overrides it.

- [x] fix shadows in iOS (remove them)

- [x] Add Read Less, when read more is expanded.

- [x] scrollable Images should be at 16:9 ratio on a box.

- [x] please check the designs again:

Screen Shot 2019-12-17 at 9 31 24 PM

- [x] @harshvitra remove `Select a planting project...` description card from All Tab in projects.

- [x] Remove {TPOName} completely from {ProjectName} by {TPOName} in both. Single view and lists.

- [x] Remove line after project cards

- [x] Rounded edges for the progress bar as below: 0,5,5,7 
Screen Shot 2019-12-28 at 2 08 06 PM

------

Fix https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1749
UI with new Project api implemented, @sagararyal 
Need more work to do to remove loadTpos api completely. I tried in this PR, but that needs much more attention on whole project,  here is the new ticket that I will work on.. https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1765

### CODE REVIEW

**Comment by harshvitra** [comment]
Screenshot_2019-12-19-20-24-39-545_org pftp

**Comment by harshvitra** [comment]
Screenshot_2019-12-19-20-24-39-545_org pftp

**Comment by harshvitra** [comment]
IMG_20191219_210228
IMG_20191219_210245

**Comment by mahmed0715** [comment]
Screenshot_20191220-213103
@sagararyal we want a divider between the projects?

**Pull request merged**
