### PR TITLE
added support for Spanish language

### PR DESCRIPTION
**Pull request by norbertschuler**
Fixes #

- [x] Not all backends yet support Spanish as e.g. the menu API call is still returning English translation. Works with https://app-development.plant-for-the-planet.org, but not with https://test.trilliontreecampaign.org/ or https://staging.trilliontreecampaign.org/ or https://www.trilliontreecampaign.org/.
- [x] Translate AppStore and GooglePlay Store title, subtitle, descriptions, keywords and meta-tags and well as release notes into Spanish.
- [x] Translate iOS permission descriptions into Spanish: https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/develop/ios/en.lproj/InfoPlist.strings

### CODE REVIEW

**Comment by norbertschuler** [comment]
Bildschirmfoto 2020-03-26 um 10 55 47

**Comment by norbertschuler** [comment]
@sagararyal I tried to add the english resources from the iOS project for permissions to the LingoHub client project at https://translate.lingohub.com/plant-for-the-planet/planet-app-(client)/edit/repository/github - but it didn't work (maybe as every project is fixed to one kind of language and resource files?)

- Should we add another project to translate the iOS permission file in `ios/en.lproj`?
- And should we also add another project to translate the resources necessary for the Google Play and Apple AppStore?

**Comment by norbertschuler** [comment]
I added two new project to LingoHub now:
- One project directly translating the iOS resource files.
- Another project translating the resources for the Google and Apple App Store with .po files.

**Comment by sagararyal** [comment]
Things to fix: [This can also be moved to a separate issue]

- [ ]  World & Leaderboard Tabs

Not sure why it keeps changing to `World Tree Map`.
  
Screen Shot 2020-04-30 at 1 08 01 PM

- [ ] Translate Country Names

Screen Shot 2020-04-30 at 1 10 17 PM

**Comment by sagararyal** [comment]
Need review:

- [ ] The app crashes when deleting tree registration on Spanish language.
Testing on Galaxy s10 Browserstack

**Comment by norbertschuler** [comment]
> * [ ]  Translate Country Names
> 
> Screen Shot 2020-04-30 at 1 10 17 PM

Country names are generally not translated yet: #879

**Comment by norbertschuler** [comment]
> Need review:
> 
> * [ ]  The app crashes when deleting tree registration on Spanish language.
>   Testing on Galaxy s10  and s8 Browserstack

I can not reproduce this issue on my Android emulator (and if there is a crash I am pretty sure it's not related to the chosen language).

**Comment by sanjayradadiya** [comment]
> Need review:
> 
> * [ ]  The app crashes when deleting tree registration on Spanish language.
>   Testing on Galaxy s10  and s8 Browserstack

@sagararyal I am also not able to reproduce in browserstack Galaxy S10 and S8

**Pull request merged**
