### PR TITLE
changed calls to register, update and delete trees to v1.3

### LINKED ISSUE #1535: Register tree: shows wrong entries in the list of own trees
**Describe the bug**
After registering a new tree, the list of trees in "My Forest" is full on undefined entries. After reloading the app (data from the backend) the list is shown correctly again.

**Is it on a Production or Development Build?**
production and develop

**To Reproduce**
1. Go to 'Trees' and register a new tree
2. Go to 'Me' and click on the tab 'My Forest'
3. See the "undefined" entries

**Expected behavior**
Just show the list of your own trees with the newly added tree.

**What actually happens**
A lot of "undefined" entries are listed in 'My Forst'

**Screenshots**
Simulator Screen Shot - iPhone 11 - 2019-10-10 at 10 45 33

**Smartphone (please complete the following information):**
- Device: iPhonex 11
 - OS: iOS 13
 - Plant-for-the-Planet App Version 1.1.0

### LINKED ISSUE #1747: API response is empty for deleting user contribution
## Error in Plant-for-the-Planet App

**TypeError** in **app/actions/EditMyTree.js:84**
undefined is not an object (evaluating 't.response.data')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df35ab18880aa0019fe630e?event_id=5df35ab10054d9e538c50000&i=gh&m=ci)

## Stacktrace

    app/actions/EditMyTree.js:84 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5df35ab18880aa0019fe630e?event_id=5df35ab10054d9e538c50000&i=gh&m=ci)

*Created automatically via Bugsnag*

### PR DESCRIPTION
**Pull request by norbertschuler**
Fixes #1747
Fixes #1535

Changes in this pull request:
- changes API call to add, update and delete user contributions to version v1.3 and merges response
- fixed bug for TPO tree registration not working if no image was provided
- fixed bug for TPOs not being able to update their tree registrations

@jmiridis I have three question for you:

- [x] I still have the problem that also with v1.3 the API call to register trees `api/v1.3/de/plantContributions/single-tree` still returns too much contributions within the treecounter object compared to the API call `api/v1.1/de/loadUserProfile`, so after this call the list of trees in my-forest is filled with unwanted entries (maybe unconfirmed).
- [ ] I also don't know why deleting a contribution and inserting a new one (register a tree) returns data objects named _competition_ and _competitionEnrollment_ - what is the purpose of these values? For now I just ignored these results, but that's probably not correct to do.
- [x] In the former version of deleting a contribution a _plantProject_ object was expected in the response. Is there still a use case where I would get such an object?

### CODE REVIEW

**Comment by jmiridis** [comment]
1. I have restricted the contributions ids returned by `/api/v1.3/de/plantContributions/single-tree` to match the contributions returned by loadUserProfile (non-verified donations are now filtered out in  both APIs)
2, Competition scores and competition enrollment scores might have been updated after a contribution (both planting or donation) have been added/deleted/updated and are therefor returned in the response as well.
3. the plan project in the response makes only sense for TPOs. They can register trees planted in their own plant projects so when such a specific contribution is updated, the number of total trees planted of the plant project entity might have been updated as well.

**Comment by norbertschuler** [comment]
If have not yet used the response objects for _competition_ and _competitionEnrollment_ to update the local database as I am not sure how to do it correctly, but I would like to merge this PR anyway as it fixes so much errors.

**Comment by sagararyal** [comment]
@norbertschuler user contribution v1.3 I think requires geometry for multiple trees.

Apps do not support them I guess. Have you checked it?

**Comment by norbertschuler** [comment]
I tested registering, updating and deleting on web client and native apps for users and TPOs with 1.3.

**Comment by norbertschuler** [comment]
> @norbertschuler user contribution v1.3 I think requires geometry for multiple trees.
> Apps do not support them I guess. Have you checked it?

The API call 1.3 for multiple trees also works well with the current old layout and form.

**Pull request merged**
